/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.example.report;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.awt.Frame;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
/**
 *
 * @author daniel
 */
public class ReportView extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("call Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(150, 150, 150).addComponent(jButton1)
                        .addContainerGap(144, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(120, 120, 120).addComponent(jButton1)
                        .addContainerGap(149, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        ConectorJ cj = new ConectorJ();
    
        Map param = new HashMap();
        param.put(0,"");

           

        try (Connection connection = cj.gConnection()) {
          

           JasperReport report = JasperCompileManager.compileReport("C:\\Users\\RyC-92\\JaspersoftWorkspace\\MyReports\\SegundoEjemplo_2.jrxml"); 
           JasperPrint jPrint = JasperFillManager.fillReport(report,null, connection);
           JasperExportManager.exportReportToPdfFile(jPrint, "c:\\Users\\RyC-92\\JaspersoftWorkspace\\MyReports\\SegundoEjemplo_2.pdf");

           JasperViewer.viewReport(jPrint, false);
       
        } catch (Exception e) {
            System.err.println(e.getMessage()); 
            System.err.println("error");
            System.err.println(e.getMessage()  + "error" + e.getClass()    );
            System.err.println(e.getStackTrace());
            

        } 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
